server:
    port: 9001
    tomcat:
        connection-timeout: 2s
        keep-alive-timeout: 15s
        threads:
            max: 50
            min-spare: 5

# spring.application.name=catalog-service
# server.port=8080

# DevTools (defaults are usually fine)
# spring.devtools.restart.enabled=true

